spring:
  application:
    name: textSearchApp
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
    connection-timeout: 10s
    socket-timeout: 30s
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123